spring.application.name=nutrixpertai

## Logging
# Show sql statement
logging.level.org.hibernate.SQL = debug

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url =${DB_CONNECTION_STRING}
spring.datasource.username = ${DB_USER}
spring.datasource.password = ${DB_PASSWORD}

api.security.token.secret=${JWT_SECRET}

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

# Swagger URL
springdoc.swagger-ui.path=/